[platformio]
src_dir = Core/Src

[env:res_controller_f103]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
build_flags =
    -I Core/Inc
    -D HSE_VALUE=8000000U
    -Wall
    -Wextra
    -Werror=return-type
monitor_speed = 115200

