/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pwm1_ucc27.c
**     Project     : NC_S32K148
**     Processor   : S32K148_144
**     Component   : pwm_pal
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2026-04-02, 09:31, # CodeGen: 49
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file pwm1_ucc27.c
** @version 01.00
*/         
/*!
**  @addtogroup pwm1_ucc27_module pwm1_ucc27 module documentation
**  @{
*/         
#include "pwm1_ucc27.h"
#include "pwm_pal.h"

/*
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External could be made static.
 * This structure is defined for usage by application code.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 8.4, external symbol defined without a prior
 * declaration.
 * This symbol is not a part of the public symbols.
 *
 */


/* Timebase */
pwm_ftm_timebase_t pwm1_ucc27Timebase =
{
    .sourceClock       = FTM_CLOCK_SOURCE_SYSTEMCLK,
    .prescaler         = FTM_CLOCK_DIVID_BY_1,
    .deadtimePrescaler = FTM_DEADTIME_DIVID_BY_1
};
 
 /* Channels */
pwm_channel_t pwm1_ucc27Channels[2] =
{
    {
        .channel                       = 2,   
        .channelType                   = PWM_EDGE_ALIGNED,      
        .period                        = 4800,
        .duty                          = 0,
        .polarity                      = PWM_ACTIVE_HIGH,
        .insertDeadtime                = false,
        .deadtime                      = 0,
        .enableComplementaryChannel    = false,
        .complementaryChannelPolarity  = PWM_DUPLICATED,
        .timebase                      = &pwm1_ucc27Timebase
    },
    {
        .channel                       = 3,   
        .channelType                   = PWM_EDGE_ALIGNED,      
        .period                        = 4800,
        .duty                          = 0,
        .polarity                      = PWM_ACTIVE_HIGH,
        .insertDeadtime                = false,
        .deadtime                      = 0,
        .enableComplementaryChannel    = false,
        .complementaryChannelPolarity  = PWM_DUPLICATED,
        .timebase                      = &pwm1_ucc27Timebase
    },
};
 
 
  /* Initialization configuration */
pwm_global_config_t pwm1_ucc27Configs =
{
    .pwmChannels          = pwm1_ucc27Channels,
    .numberOfPwmChannels  = 2,
};
 
  /* Instance configuration */
pwm_instance_t pwm1_ucc27Instance =
{
    .instType  = PWM_INST_TYPE_FTM,
    .instIdx   = 1,
};
  
 
/* END pwm1_ucc27. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

