function apply_rule_compliance_20260731()
%APPLY_RULE_COMPLIANCE_20260731 Apply the 2026 FSEC rule safety corrections.
% 修改边界：仅修改 Simulink 模型及其数据字典，不修改底层软件、任务架构和根接口。
% 依据：2026 赛事规则 AV1.5、AV2.3、AV2.6、AV2.7、AV3.2、AV3.3，
%       以及 2025 无人系统技术检查表第 323、330～354 项。

modelDir = 'C:\Users\icemi\Desktop\RZS_Repository\VCU';
model = 'VCU10';
modelFile = fullfile(modelDir, [model '.slx']);
dictionaryFile = fullfile(modelDir, 'VCU10DB.sldd');
backupDir = fullfile(modelDir, ...
    'Model_Backup_20260731_before_rule_compliance');

if ~exist(backupDir, 'dir')
    mkdir(backupDir);
end
if ~exist(fullfile(backupDir, [model '.slx']), 'file')
    copyfile(modelFile, fullfile(backupDir, [model '.slx']));
end
if ~exist(fullfile(backupDir, 'VCU10DB.sldd'), 'file')
    copyfile(dictionaryFile, fullfile(backupDir, 'VCU10DB.sldd'));
end

oldDir = pwd;
cleanupDir = onCleanup(@() cd(oldDir));
cd(modelDir);
load_system(model);
cleanupModel = onCleanup(@() close_system(model, 0));
root = sfroot;

%% 1. AS 状态机：Emergency 保持转向、触发 EBS，并在 Finished 后锁止重启。
asChart = root.find('-isa', 'Stateflow.Chart', ...
    'Path', [model '/AS_Stateflow/Chart']);
assert(~isempty(asChart), 'Cannot find AS Stateflow chart.');

set_state_label(asChart, 'AS_Emergency', sprintf([ ...
    'AS_Emergency\n' ...
    'ts_flag=0;\n' ...
    'r2d_flag=0;\n' ...
    'steering_flag=1;\n' ...
    'brake_flag=1;\n' ...
    'ebs_system_flag=2;\n' ...
    'as_ebs_trig=1;\n' ...
    'as_led_yellow=0;\n' ...
    'as_led_blue=2;\n' ...
    'as_off_flag=0;\n' ...
    'as_ready_flag=0;\n' ...
    'as_driving_flag=0;\n' ...
    'as_finished_flag=0;\n' ...
    'as_emergency_flag=1;\n' ...
    'manual_driving_flag=0;\n' ...
    'safety_lock=1;']));

set_state_label(asChart, 'AS_Finished', sprintf([ ...
    'AS_Finished\n' ...
    'ts_flag=0;\n' ...
    'r2d_flag=0;\n' ...
    'steering_flag=0;\n' ...
    'brake_flag=0;\n' ...
    'ebs_system_flag=2;\n' ...
    'as_ebs_trig=1;\n' ...
    'as_led_yellow=0;\n' ...
    'as_led_blue=1;\n' ...
    'as_off_flag=0;\n' ...
    'as_ready_flag=0;\n' ...
    'as_driving_flag=0;\n' ...
    'as_finished_flag=1;\n' ...
    'as_emergency_flag=0;\n' ...
    'manual_driving_flag=0;\n' ...
    'safety_lock=1;']));

offState = find_state(asChart, 'AS_Off');
if isempty(strfind(offState.LabelString, 'as_ebs_trig=0')) %#ok<STREMP>
    offState.LabelString = sprintf('%s\nas_ebs_trig=0;', ...
        offState.LabelString);
end
readyState = find_state(asChart, 'AS_Ready');
if isempty(strfind(readyState.LabelString, 'as_ebs_trig=0')) %#ok<STREMP>
    readyState.LabelString = sprintf('%s\nas_ebs_trig=0;', ...
        readyState.LabelString);
end
manualState = find_state(asChart, 'Manual_Driving');
if isempty(strfind(manualState.LabelString, 'as_ebs_trig=0')) %#ok<STREMP>
    manualState.LabelString = sprintf('%s\nas_ebs_trig=0;', ...
        manualState.LabelString);
end

ensure_annotation([model '/AS_Stateflow'], ...
    ['2026 规则：Emergency 时切断驱动并触发 EBS；车辆仍运动时转向保持可用。' ...
     'Emergency 与 Finished 均锁存，必须低压重启后才能再次进入 Ready。'], ...
    [310 10 1140 62]);

%% 2. 修复 RES 与 ESP 生命信号恢复时计数器未清零的问题。
reset_recovery_counter(root, ...
    [model '/Res/Res_Msg/Subsystem/heaartbeat_chart'], 'hbcnt');
reset_recovery_counter(root, ...
    [model '/ESP/ESP_ReceiveMsg/Subsystem/brkmotor_check_system'], 'lscnt');

%% 3. EPS 协议及 SCS：控制模式改为说明书规定的 0x10。
epsChart = root.find('-isa', 'Stateflow.Chart', ...
    'Path', [model '/EPS/EPS_TransmitMsg/EPS_Stateflow1']);
assert(~isempty(epsChart), 'Cannot find EPS transmit chart.');
epsStates = epsChart.find('-isa', 'Stateflow.State');
for index = 1:numel(epsStates)
    if strcmp(epsStates(index).Name, 'EPS_Enable') || ...
            strcmp(epsStates(index).Name, 'EPS_Return')
        epsStates(index).LabelString = strrep( ...
            epsStates(index).LabelString, '0x20', '0x10');
    end
end

epsMonitor = [model '/EPS_SCS_Monitor'];
if getSimulinkBlockHandle(epsMonitor) == -1
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        epsMonitor, 'Position', [850 1040 1075 1145]);
end
epsMonitorChart = find_em_chart(root, epsMonitor);
epsMonitorChart.Script = eps_monitor_script();
clear_all_input_lines(epsMonitor);
add_line(model, 'canb_epssendmsg1/1', 'EPS_SCS_Monitor/1', ...
    'autorouting', 'on');
add_line(model, 'canb_epssendmsg2/1', 'EPS_SCS_Monitor/2', ...
    'autorouting', 'on');
set_param(model, 'SimulationCommand', 'update');
ensure_annotation(model, ...
    ['EPS SCS：校验 0x401 的 XOR、错误码和 0x402 发送计数。连续 300 ms ' ...
     '无新计数或连续异常时进入安全故障；连续有效 500 ms 后恢复。'], ...
    [760 1015 1440 1062]);

%% 4. 综合安全故障加入 IPC 与 EPS；EBS 故障灯不再被 RES 故障误点亮。
safetyOr = [model '/FSEC_Safety_Fault_OR'];
set_param(safetyOr, 'Inputs', '4');
clear_all_input_lines(safetyOr);
add_line(model, 'ASB_Selfcheck/3', 'FSEC_Safety_Fault_OR/1', ...
    'autorouting', 'on');
add_line(model, 'EBS/5', 'FSEC_Safety_Fault_OR/2', ...
    'autorouting', 'on');
add_line(model, 'From31/1', 'FSEC_Safety_Fault_OR/3', ...
    'autorouting', 'on');
add_line(model, 'EPS_SCS_Monitor/1', 'FSEC_Safety_Fault_OR/4', ...
    'autorouting', 'on');

asbSystem = [model '/ASB_Selfcheck'];
sensorMonitor = [asbSystem '/FSEC_Sensor_Monitor'];
sensorMonitorChart = find_em_chart(root, sensorMonitor);
sensorMonitorChart.Script = sensor_monitor_script();
set_param(model, 'SimulationCommand', 'update');

ebsFaultOut = [asbSystem '/ebs_fault_indicator'];
if getSimulinkBlockHandle(ebsFaultOut) == -1
    add_block('simulink/Sinks/Out1', ebsFaultOut, 'Port', '4', ...
        'OutDataTypeStr', 'boolean', 'Position', [915 505 945 525]);
end
delete_input_line(ebsFaultOut, 1);
add_line(asbSystem, 'FSEC_Sensor_Monitor/5', ...
    'ebs_fault_indicator/1', 'autorouting', 'on');

ebsErrorOr = [model '/FSEC_EBS_Error_OR'];
set_param(ebsErrorOr, 'Inputs', '3');
clear_all_input_lines(ebsErrorOr);
add_line(model, 'LED_Control/4', 'FSEC_EBS_Error_OR/1', ...
    'autorouting', 'on');
add_line(model, 'ASB_Selfcheck/4', 'FSEC_EBS_Error_OR/2', ...
    'autorouting', 'on');
add_line(model, 'EBS/5', 'FSEC_EBS_Error_OR/3', ...
    'autorouting', 'on');

ensure_annotation(asbSystem, ...
    ['故障分类：RES、IPC、EPS 故障触发安全状态，但不冒充 EBS 本体故障；' ...
     '气压、制动传感器、ESP 冗余制动或 EBS_Driver 故障才点亮 EBS 红灯。'], ...
    [420 12 1120 68]);

%% 5. EBS 输出：取消“自检状态任意跳变即触发”，仅由 Emergency/Finished 请求。
ebsSystem = [model '/EBS'];
delete_input_line([ebsSystem '/ebs_trig'], 1);
delete_input_line([ebsSystem '/EBS_Response_Monitor'], 1);
oldBlocks = {'Edge Detector', 'Edge Detector2', 'Logical Operator'};
for index = 1:numel(oldBlocks)
    path = [ebsSystem '/' oldBlocks{index}];
    if getSimulinkBlockHandle(path) ~= -1
        delete_block(path);
    end
end
triggerGate = [ebsSystem '/EBS_Trigger_ASMS_Gate'];
if getSimulinkBlockHandle(triggerGate) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        triggerGate, 'Operator', 'AND', 'Inputs', '2', ...
        'Position', [455 190 520 235]);
end
clear_all_input_lines(triggerGate);
add_line(ebsSystem, 'as_ebs_trig/1', 'EBS_Trigger_ASMS_Gate/1', ...
    'autorouting', 'on');
add_line(ebsSystem, 'Bus Selector/1', 'EBS_Trigger_ASMS_Gate/2', ...
    'autorouting', 'on');
add_line(ebsSystem, 'EBS_Trigger_ASMS_Gate/1', 'ebs_trig/1', ...
    'autorouting', 'on');
add_line(ebsSystem, 'EBS_Trigger_ASMS_Gate/1', ...
    'EBS_Response_Monitor/1', 'autorouting', 'on');

ebsResponseChart = find_em_chart(root, ...
    [ebsSystem '/EBS_Response_Monitor']);
ebsResponseChart.Script = ebs_monitor_script();
ensure_annotation(ebsSystem, ...
    ['EBS 命令仅在 ASMS 有效且状态机进入 Emergency/Finished 时输出。' ...
     'ASMS 关闭时由非可编程硬件断电触发被动 EBS，软件命令保持关闭。' ...
     '触发后 200 ms 内未检测到下游建压则报告 EBS 故障。'], ...
    [300 8 1120 72]);

%% 6. EBS 指示灯：下游气压在未触发时允许为零，避免正常状态误报。
ebsLed = [model '/LED_Control/EBS_LED'];
ebsLedOr = [ebsLed '/Logical Operator'];
set_param(ebsLedOr, 'Inputs', '4');
clear_all_input_lines(ebsLedOr);
add_line(ebsLed, 'Compare To Constant/1', 'Logical Operator/1', ...
    'autorouting', 'on');
add_line(ebsLed, 'Enabled Subsystem/1', 'Logical Operator/2', ...
    'autorouting', 'on');
add_line(ebsLed, 'Logical Operator3/1', 'Logical Operator/3', ...
    'autorouting', 'on');
add_line(ebsLed, 'display/1', 'Logical Operator/4', ...
    'autorouting', 'on');
ensure_annotation(ebsLed, ...
    ['气缸侧气压在 EBS 未触发时可以接近 0 bar，不能单独作为断线故障。' ...
     '该传感器通过量程上限、两路合理性及触发后 200 ms 建压响应进行诊断。'], ...
    [80 470 760 520]);

%% 7. ASSI：由 AS 状态唯一决定，蓝灯在 ASMS 断开后的 Emergency 阶段仍闪烁。
update_assi_chart(root, [model '/LED_Control/Subsystem/blue'], ...
    'as_led_blue');
update_assi_chart(root, [model '/LED_Control/Subsystem1/yellow'], ...
    'as_led_yellow');
set_pulse_2hz([model '/LED_Control/Subsystem/Pulse Generator']);
set_pulse_2hz([model '/LED_Control/Subsystem1/Pulse Generator']);
ensure_annotation([model '/LED_Control'], ...
    ['ASSI 闪烁频率 2 Hz、占空比 50%。指示只跟随 AS 状态；' ...
     'Emergency 蓝闪不会因 ASMS 刚断开而提前熄灭。'], ...
    [450 8 1040 55]);

%% 8. APPS 单通道开路/短路：原始 0～5 V 信号越界时立即撤销手动转矩。
manualTorque = [model '/Motor_Control/ManualTorque_Calculation'];
manualSelector = [manualTorque '/Bus Selector'];
set_param(manualSelector, 'OutputSignals', ...
    'apps1_01,apps2_01,apps1_raw,apps2_raw');

appsMonitor = [manualTorque '/APPS_Electrical_Monitor'];
if getSimulinkBlockHandle(appsMonitor) == -1
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        appsMonitor, 'Position', [420 465 635 570]);
end
appsMonitorChart = find_em_chart(root, appsMonitor);
appsMonitorChart.Script = apps_monitor_script();
clear_all_input_lines(appsMonitor);
add_line(manualTorque, 'Bus Selector/3', ...
    'APPS_Electrical_Monitor/1', 'autorouting', 'on');
add_line(manualTorque, 'Bus Selector/4', ...
    'APPS_Electrical_Monitor/2', 'autorouting', 'on');
set_param(model, 'SimulationCommand', 'update');

appsGate = [manualTorque '/APPS_Torque_Valid_Gate'];
if getSimulinkBlockHandle(appsGate) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        appsGate, 'Operator', 'AND', 'Inputs', '2', ...
        'Position', [735 325 790 375]);
end
clear_all_input_lines(appsGate);
delete_input_line([manualTorque '/Switch'], 2);
add_line(manualTorque, 'Logical Operator/1', ...
    'APPS_Torque_Valid_Gate/1', 'autorouting', 'on');
add_line(manualTorque, 'APPS_Electrical_Monitor/1', ...
    'APPS_Torque_Valid_Gate/2', 'autorouting', 'on');
add_line(manualTorque, 'APPS_Torque_Valid_Gate/1', 'Switch/2', ...
    'autorouting', 'on');

appsFaultTerminator = [manualTorque '/APPS_Fault_Terminator'];
if getSimulinkBlockHandle(appsFaultTerminator) == -1
    add_block('simulink/Sinks/Terminator', appsFaultTerminator, ...
        'Position', [675 535 695 555]);
end
delete_input_line(appsFaultTerminator, 1);
add_line(manualTorque, 'APPS_Electrical_Monitor/2', ...
    'APPS_Fault_Terminator/1', 'autorouting', 'on');
ensure_annotation(manualTorque, ...
    ['APPS：双通道差值仍按 10% 检查；任一原始 ADC 低于 0.10 V 或高于 ' ...
     '4.90 V 时立即将转矩置零，100 ms 确认故障，连续正常 500 ms 恢复。' ...
     '阈值需在踏板最终标定后复核。'], ...
    [350 585 1080 655]);

%% 9. Emergency 液压冗余制动：ASMS 有效时四轮请求 8 MPa。
set_dictionary_parameter(dictionaryFile, ...
    'FSEC_ESP_EMERGENCY_PRESSURE_MPA', 8.0, 'MPa', ...
    'AS Emergency 时 ESP 四轮冗余制动压力；实车制动标定后复核。');
add_emergency_esp_override(model);

%% 10. 保存并执行最终模型更新。
ensure_annotation(model, ...
    ['2026 车检规则修正（2026-07-31）：Emergency 转向/EBS、Finished 锁止、' ...
     'ASSI 2 Hz、RES/ESP 心跳恢复、EPS SCS 与 0x10 模式、APPS 开短路、' ...
     'EBS 故障分类及 ESP 冗余制动。根接口及底层软件未改变。'], ...
    [690 10 1660 78]);

set_param(model, 'SimulationCommand', 'update');
save_system(model);
fprintf('RULE_COMPLIANCE_UPDATE=PASS\n');
fprintf('MODEL=%s\n', modelFile);
fprintf('MODEL_VERSION=%s\n', get_param(model, 'ModelVersion'));
fprintf('ROOT_INPUTS=%d ROOT_OUTPUTS=%d\n', ...
    numel(find_system(model, 'SearchDepth', 1, 'BlockType', 'Inport')), ...
    numel(find_system(model, 'SearchDepth', 1, 'BlockType', 'Outport')));

clear cleanupModel cleanupDir;
end

function set_state_label(chart, stateName, label)
state = find_state(chart, stateName);
state.LabelString = label;
end

function state = find_state(chart, stateName)
state = chart.find('-isa', 'Stateflow.State', 'Name', stateName);
assert(~isempty(state), 'Cannot find Stateflow state %s.', stateName);
state = state(1);
end

function reset_recovery_counter(root, chartPath, counterName)
chart = root.find('-isa', 'Stateflow.Chart', 'Path', chartPath);
assert(~isempty(chart), 'Cannot find chart %s.', chartPath);
transitions = chart.find('-isa', 'Stateflow.Transition');
for index = 1:numel(transitions)
    item = transitions(index);
    if isa(item.Source, 'Stateflow.State') && ...
            isa(item.Destination, 'Stateflow.State') && ...
            strcmp(item.Source.Name, 'judge') && ...
            strcmp(item.Destination.Name, 'compare')
        item.LabelString = sprintf('[hasChanged(%s)]{%s=0}', ...
            input_name_for_counter(counterName), counterName);
        return;
    end
end
error('Cannot find judge-to-compare recovery transition in %s.', chartPath);
end

function name = input_name_for_counter(counterName)
if strcmp(counterName, 'hbcnt')
    name = 'res_heartbeat';
else
    name = 'lifesig';
end
end

function update_assi_chart(root, chartPath, signalName)
chart = root.find('-isa', 'Stateflow.Chart', 'Path', chartPath);
assert(~isempty(chart), 'Cannot find ASSI chart %s.', chartPath);
transitions = chart.find('-isa', 'Stateflow.Transition');
for index = 1:numel(transitions)
    item = transitions(index);
    if ~isa(item.Destination, 'Stateflow.State')
        continue;
    end
    destination = item.Destination.Name;
    if strcmp(destination, 'Blink')
        item.LabelString = sprintf('[%s==2]', signalName);
    elseif strcmp(destination, 'On')
        item.LabelString = sprintf('[%s==1]', signalName);
    elseif strcmp(destination, 'Close')
        item.LabelString = sprintf('[%s==0]', signalName);
    end
end
end

function set_pulse_2hz(block)
set_param(block, 'Period', '50', 'PulseWidth', '25', ...
    'PhaseDelay', '0', 'SampleTime', '-1');
end

function add_emergency_esp_override(model)
esp = [model '/ESP'];
espTx = [esp '/ESP_TransmitMsg'];
espFrame = [espTx '/ESP_R_00'];

ensure_inport(esp, 'asms', 7, [-1320 718 -1290 732]);
ensure_inport(espTx, 'asms', 5, [910 848 940 862]);
ensure_inport(espFrame, 'asms', 5, [-40 478 -10 492]);
set_param(model, 'SimulationCommand', 'update');

delete_input_line(espTx, 5);
delete_input_line(espFrame, 5);
add_line(esp, 'asms/1', 'ESP_TransmitMsg/5', 'autorouting', 'on');
add_line(espTx, 'asms/1', 'ESP_R_00/5', 'autorouting', 'on');

delete_input_line(esp, 7);
add_line(model, 'Bus Selector6/1', 'ESP/7', 'autorouting', 'on');

emergencyRead = [espFrame '/AS_Emergency_Read'];
if getSimulinkBlockHandle(emergencyRead) == -1
    add_block('simulink/Signal Routing/Data Store Read', emergencyRead, ...
        'DataStoreName', 'as_emergency_flag', ...
        'Position', [-180 500 -55 530]);
end
enable = [espFrame '/Emergency_Hydraulic_Backup_Enable'];
if getSimulinkBlockHandle(enable) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        enable, 'Operator', 'AND', 'Inputs', '2', ...
        'Position', [5 485 65 530]);
end
clear_all_input_lines(enable);
add_line(espFrame, 'AS_Emergency_Read/1', ...
    'Emergency_Hydraulic_Backup_Enable/1', 'autorouting', 'on');
add_line(espFrame, 'asms/1', ...
    'Emergency_Hydraulic_Backup_Enable/2', 'autorouting', 'on');

pressure = [espFrame '/Emergency_Pressure_MPa'];
if getSimulinkBlockHandle(pressure) == -1
    add_block('simulink/Sources/Constant', pressure, ...
        'Value', 'FSEC_ESP_EMERGENCY_PRESSURE_MPA', ...
        'OutDataTypeStr', 'double', 'Position', [-25 545 125 575]);
end

for channel = 1:4
    switchName = sprintf('Emergency_Pressure_Select_%d', channel);
    switchPath = [espFrame '/' switchName];
    if getSimulinkBlockHandle(switchPath) == -1
        y = 65 + (channel - 1) * 80;
        add_block('simulink/Signal Routing/Switch', switchPath, ...
            'Criteria', 'u2 >= Threshold', 'Threshold', '0.5', ...
            'Position', [-5 y 45 (y + 55)]);
    end
    clear_all_input_lines(switchPath);
    delete_input_line([espFrame '/ESP_Chart1'], channel);
    add_line(espFrame, 'Emergency_Pressure_MPa/1', ...
        [switchName '/1'], 'autorouting', 'on');
    add_line(espFrame, 'Emergency_Hydraulic_Backup_Enable/1', ...
        [switchName '/2'], 'autorouting', 'on');
    add_line(espFrame, sprintf('Bus Selector/%d', channel), ...
        [switchName '/3'], 'autorouting', 'on');
    add_line(espFrame, [switchName '/1'], ...
        sprintf('ESP_Chart1/%d', channel), 'autorouting', 'on');
end

ensure_annotation(espFrame, ...
    ['Emergency 且 ASMS 有效时，ESP 四轮目标压力覆盖为 8 MPa，作为 EBS ' ...
     '单一故障时的相互监控制动冗余。ASMS 关闭后硬件切断制动执行器能源。' ...
     '该压力必须通过实车减速度与稳定性试验后最终标定。'], ...
    [-210 580 760 650]);
end

function ensure_inport(system, name, port, position)
path = [system '/' name];
if getSimulinkBlockHandle(path) == -1
    add_block('simulink/Sources/In1', path, 'Port', num2str(port), ...
        'OutDataTypeStr', 'boolean', 'Position', position);
else
    set_param(path, 'Port', num2str(port));
end
end

function set_dictionary_parameter(dictionaryFile, name, value, unit, description)
dictionary = Simulink.data.dictionary.open(dictionaryFile);
section = getSection(dictionary, 'Design Data');
parameter = Simulink.Parameter;
parameter.Value = value;
parameter.DataType = 'double';
parameter.Unit = unit;
parameter.Description = description;
try
    entry = getEntry(section, name);
    setValue(entry, parameter);
catch
    addEntry(section, name, parameter);
end
saveChanges(dictionary);
end

function text = sensor_monitor_script()
text = sprintf([ ...
    'function [brake_sensor_valid, safety_fault, brake_sensor_fault, air_sensor_fault, ebs_fault_indicator] = fsec_sensor_monitor(brake_raw_mv, air_ready_raw_mv, air_work_raw_mv, air_ready_bar, air_work_bar, esp_ok, res_ok, ebs_driver_ok)\n' ...
    '%%#codegen\n' ...
    '%% 制动踏板为 0-5 V；两路气压为 0-10 V。阈值需在最终标定后复核。\n' ...
    'persistent brake_bad brake_good air_bad air_good comm_bad comm_good ebs_bad ebs_good brake_fault air_fault comm_fault ebs_comm_fault\n' ...
    'if isempty(brake_bad)\n' ...
    '    brake_bad=uint16(0); brake_good=uint16(0); air_bad=uint16(0); air_good=uint16(0);\n' ...
    '    comm_bad=uint16(0); comm_good=uint16(0); ebs_bad=uint16(0); ebs_good=uint16(0);\n' ...
    '    brake_fault=false; air_fault=false; comm_fault=false; ebs_comm_fault=false;\n' ...
    'end\n' ...
    'brake_now = (brake_raw_mv < 100.0) || (brake_raw_mv > 4900.0);\n' ...
    'if brake_now\n' ...
    '    brake_good=uint16(0); if brake_bad<uint16(1000), brake_bad=brake_bad+uint16(1); end\n' ...
    '    if brake_bad>=uint16(10), brake_fault=true; end\n' ...
    'else\n' ...
    '    brake_bad=uint16(0); if brake_good<uint16(1000), brake_good=brake_good+uint16(1); end\n' ...
    '    if brake_good>=uint16(50), brake_fault=false; end\n' ...
    'end\n' ...
    '%% 储气侧低压可直接阻止 Ready；下游低压仅在 EBS 触发后由响应监控判断。\n' ...
    'air_now = (air_ready_raw_mv > 9800.0) || (air_work_raw_mv > 9800.0) || ...\n' ...
    '          (air_ready_bar < 2.5) || (air_work_bar > air_ready_bar + 1.5);\n' ...
    'if air_now\n' ...
    '    air_good=uint16(0); if air_bad<uint16(1000), air_bad=air_bad+uint16(1); end\n' ...
    '    if air_bad>=uint16(50), air_fault=true; end\n' ...
    'else\n' ...
    '    air_bad=uint16(0); if air_good<uint16(1000), air_good=air_good+uint16(1); end\n' ...
    '    if air_good>=uint16(50), air_fault=false; end\n' ...
    'end\n' ...
    'comm_now = (~logical(esp_ok)) || (~logical(res_ok)) || (~logical(ebs_driver_ok));\n' ...
    'if comm_now\n' ...
    '    comm_good=uint16(0); if comm_bad<uint16(1000), comm_bad=comm_bad+uint16(1); end\n' ...
    '    if comm_bad>=uint16(30), comm_fault=true; end\n' ...
    'else\n' ...
    '    comm_bad=uint16(0); if comm_good<uint16(1000), comm_good=comm_good+uint16(1); end\n' ...
    '    if comm_good>=uint16(50), comm_fault=false; end\n' ...
    'end\n' ...
    '%% EBS 红灯只显示 EBS/制动冗余本体故障，不显示 RES 一般安全事件。\n' ...
    'ebs_comm_now = (~logical(esp_ok)) || (~logical(ebs_driver_ok));\n' ...
    'if ebs_comm_now\n' ...
    '    ebs_good=uint16(0); if ebs_bad<uint16(1000), ebs_bad=ebs_bad+uint16(1); end\n' ...
    '    if ebs_bad>=uint16(30), ebs_comm_fault=true; end\n' ...
    'else\n' ...
    '    ebs_bad=uint16(0); if ebs_good<uint16(1000), ebs_good=ebs_good+uint16(1); end\n' ...
    '    if ebs_good>=uint16(50), ebs_comm_fault=false; end\n' ...
    'end\n' ...
    'brake_sensor_valid = (~brake_fault) && (~brake_now);\n' ...
    'brake_sensor_fault = brake_fault;\n' ...
    'air_sensor_fault = air_fault;\n' ...
    'safety_fault = brake_fault || air_fault || comm_fault;\n' ...
    'ebs_fault_indicator = brake_fault || air_fault || ebs_comm_fault;\n' ...
    'end\n']);
end

function text = ebs_monitor_script()
text = sprintf([ ...
    'function ebs_sensor_fault = ebs_response_monitor(trigger, asms, driver_ok, air_ready_bar, air_work_bar)\n' ...
    '%%#codegen\n' ...
    '%% EBS_Driver 负责电气诊断；VCU 校验触发后的气动建压响应。\n' ...
    'persistent last_trigger waiting wait_count relation_count clear_count fault_latched\n' ...
    'if isempty(last_trigger)\n' ...
    '    last_trigger=false; waiting=false; wait_count=uint16(0); relation_count=uint16(0);\n' ...
    '    clear_count=uint16(0); fault_latched=false;\n' ...
    'end\n' ...
    'rising = logical(trigger) && ~last_trigger; last_trigger=logical(trigger);\n' ...
    'if rising && logical(driver_ok) && (air_ready_bar >= 2.5) && (air_work_bar < 1.0)\n' ...
    '    waiting=true; wait_count=uint16(0);\n' ...
    'end\n' ...
    'if waiting\n' ...
    '    if air_work_bar >= 1.0\n' ...
    '        waiting=false; wait_count=uint16(0);\n' ...
    '    else\n' ...
    '        if wait_count<uint16(1000), wait_count=wait_count+uint16(1); end\n' ...
    '        if wait_count>=uint16(20), fault_latched=true; waiting=false; end\n' ...
    '    end\n' ...
    'end\n' ...
    'if air_work_bar > air_ready_bar + 1.5\n' ...
    '    if relation_count<uint16(1000), relation_count=relation_count+uint16(1); end\n' ...
    '    if relation_count>=uint16(20), fault_latched=true; end\n' ...
    'else\n' ...
    '    relation_count=uint16(0);\n' ...
    'end\n' ...
    'if (~logical(asms)) && logical(driver_ok) && (air_work_bar < 1.0) && (air_ready_bar >= 2.5)\n' ...
    '    if clear_count<uint16(1000), clear_count=clear_count+uint16(1); end\n' ...
    '    if clear_count>=uint16(100), fault_latched=false; end\n' ...
    'else\n' ...
    '    clear_count=uint16(0);\n' ...
    'end\n' ...
    'ebs_sensor_fault = fault_latched;\n' ...
    'end\n']);
end

function text = eps_monitor_script()
text = sprintf([ ...
    'function eps_safety_fault = eps_scs_monitor(msg1, msg2)\n' ...
    '%%#codegen\n' ...
    '%% 0x401: Byte7 = XOR(Byte0..Byte6); 0x402: Byte1 为发送计数。\n' ...
    'persistent last_counter seen_count stale_count bad_count good_count fault\n' ...
    'if isempty(last_counter)\n' ...
    '    last_counter=msg2(2); seen_count=uint16(0); stale_count=uint16(0);\n' ...
    '    bad_count=uint16(0); good_count=uint16(0); fault=true;\n' ...
    'end\n' ...
    'counter=msg2(2);\n' ...
    'if counter~=last_counter\n' ...
    '    last_counter=counter; stale_count=uint16(0);\n' ...
    '    if seen_count<uint16(1000), seen_count=seen_count+uint16(1); end\n' ...
    'else\n' ...
    '    if stale_count<uint16(1000), stale_count=stale_count+uint16(1); end\n' ...
    'end\n' ...
    'checksum=uint8(0);\n' ...
    'for k=1:7\n' ...
    '    checksum=bitxor(checksum,msg1(k));\n' ...
    'end\n' ...
    'content_valid=(checksum==msg1(8)) && (msg1(3)==uint8(0)) && (msg1(7)==uint8(0));\n' ...
    'fresh=(seen_count>=uint16(3)) && (stale_count<uint16(30));\n' ...
    'valid_now=content_valid && fresh;\n' ...
    'if valid_now\n' ...
    '    bad_count=uint16(0); if good_count<uint16(1000), good_count=good_count+uint16(1); end\n' ...
    '    if good_count>=uint16(50), fault=false; end\n' ...
    'else\n' ...
    '    good_count=uint16(0); if bad_count<uint16(1000), bad_count=bad_count+uint16(1); end\n' ...
    '    if (bad_count>=uint16(3)) || (stale_count>=uint16(30)), fault=true; end\n' ...
    'end\n' ...
    'eps_safety_fault=fault;\n' ...
    'end\n']);
end

function text = apps_monitor_script()
text = sprintf([ ...
    'function [apps_valid, apps_electrical_fault] = apps_electrical_monitor(apps1_raw_mv, apps2_raw_mv)\n' ...
    '%%#codegen\n' ...
    '%% 0-5 V APPS 单通道开路/短路诊断；最终阈值由实车标定确认。\n' ...
    'persistent bad_count good_count fault\n' ...
    'if isempty(bad_count)\n' ...
    '    bad_count=uint16(0); good_count=uint16(0); fault=false;\n' ...
    'end\n' ...
    'bad_now=(apps1_raw_mv<100.0)||(apps1_raw_mv>4900.0)||...\n' ...
    '        (apps2_raw_mv<100.0)||(apps2_raw_mv>4900.0);\n' ...
    'if bad_now\n' ...
    '    good_count=uint16(0); if bad_count<uint16(1000), bad_count=bad_count+uint16(1); end\n' ...
    '    if bad_count>=uint16(10), fault=true; end\n' ...
    'else\n' ...
    '    bad_count=uint16(0); if good_count<uint16(1000), good_count=good_count+uint16(1); end\n' ...
    '    if good_count>=uint16(50), fault=false; end\n' ...
    'end\n' ...
    'apps_valid=(~bad_now) && (~fault);\n' ...
    'apps_electrical_fault=fault;\n' ...
    'end\n']);
end

function chart = find_em_chart(root, blockPath)
charts = root.find('-isa', 'Stateflow.EMChart');
chart = [];
for index = 1:numel(charts)
    fullPath = [charts(index).Path '/' charts(index).Name];
    if strcmp(charts(index).Path, blockPath) || strcmp(fullPath, blockPath)
        chart = charts(index);
        break;
    end
end
if isempty(chart)
    error('MATLAB Function chart not found for %s.', blockPath);
end
end

function delete_input_line(block, portNumber)
handles = get_param(block, 'LineHandles');
if isfield(handles, 'Inport') && portNumber <= numel(handles.Inport) && ...
        handles.Inport(portNumber) ~= -1
    delete_line(handles.Inport(portNumber));
end
end

function clear_all_input_lines(block)
handles = get_param(block, 'LineHandles');
if ~isfield(handles, 'Inport')
    return;
end
for index = 1:numel(handles.Inport)
    if handles.Inport(index) ~= -1
        delete_line(handles.Inport(index));
    end
end
end

function ensure_annotation(system, text, position)
annotations = find_system(system, 'FindAll', 'on', 'SearchDepth', 1, ...
    'Type', 'annotation');
for index = 1:numel(annotations)
    if strcmp(get_param(annotations(index), 'PlainText'), text)
        return;
    end
end
annotation = Simulink.Annotation(system, text);
annotation.Position = position;
end
