function optimize_fsec_safety_model()
%OPTIMIZE_FSEC_SAFETY_MODEL Add preliminary FSEC safety diagnostics.
% Root model I/O, the function-call schedule and the hand-written software
% architecture are preserved. The vehicle netlist remains the authority for
% physical signal assignment.

modelDir = 'C:\Users\icemi\Desktop\RZS_Repository\VCU\Models\DBC_Debug';
model = 'VCU10';
modelFile = fullfile(modelDir, [model '.slx']);
dictionaryFile = fullfile(modelDir, 'VCU10DB.sldd');
backupDir = fullfile(modelDir, 'Backup_20260729_before_fsec_safety');

if ~exist(backupDir, 'dir')
    mkdir(backupDir);
    copyfile(modelFile, fullfile(backupDir, [model '.slx']));
    copyfile(dictionaryFile, fullfile(backupDir, 'VCU10DB.sldd'));
end

oldDir = pwd;
cleanupDir = onCleanup(@() cd(oldDir));
cd(modelDir);
load_system(model);
cleanupModel = onCleanup(@() close_system(model, 0));
root = sfroot;

%% Retain raw pressure voltages in the existing sensor bus.
sensorSystem = [model '/Sensor_Signal'];
sensorBus = [sensorSystem '/Bus Creator'];
set_param(sensorBus, 'Inputs', '12');
replace_input_line(sensorBus, 11, sensorSystem, ...
    'airprs_sensor1/1', 'Bus Creator/11', 'airprs1_raw');
replace_input_line(sensorBus, 12, sensorSystem, ...
    'airprs_sensor2/1', 'Bus Creator/12', 'airprs2_raw');

ensure_annotation(sensorSystem, ...
    ['FSEC diagnostics: brkps_raw is checked against 0.10-4.90 V. ' ...
     'Air pressure sensor 1 is the reservoir/ready side; sensor 2 is ' ...
     'the solenoid downstream/cylinder side.'], ...
    [170 55 980 100]);

%% Add debounced brake, pressure-plausibility and communication diagnostics.
asbSystem = [model '/ASB_Selfcheck'];
asbSelector = [asbSystem '/Bus Selector'];
set_param(asbSelector, 'OutputSignals', ...
    ['airprs_sensor1,brkps_raw,airprs1_raw,airprs2_raw,' ...
     'airprs_sensor2']);

monitorBlock = [asbSystem '/FSEC_Sensor_Monitor'];
if getSimulinkBlockHandle(monitorBlock) == -1
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        monitorBlock, 'Position', [560 390 760 535]);
end
monitorChart = find_em_chart(root, monitorBlock);
monitorChart.Script = sensor_monitor_script();

% The MATLAB Function ports are rebuilt immediately after setting Script.
set_param(model, 'SimulationCommand', 'update');
clear_all_input_lines(monitorBlock);
add_line(asbSystem, 'Bus Selector/2', 'FSEC_Sensor_Monitor/1', ...
    'autorouting', 'on');
add_line(asbSystem, 'Bus Selector/3', 'FSEC_Sensor_Monitor/2', ...
    'autorouting', 'on');
add_line(asbSystem, 'Bus Selector/4', 'FSEC_Sensor_Monitor/3', ...
    'autorouting', 'on');
add_line(asbSystem, 'Bus Selector/1', 'FSEC_Sensor_Monitor/4', ...
    'autorouting', 'on');
add_line(asbSystem, 'Bus Selector/5', 'FSEC_Sensor_Monitor/5', ...
    'autorouting', 'on');
add_line(asbSystem, 'brkmotor_check/1', 'FSEC_Sensor_Monitor/6', ...
    'autorouting', 'on');
add_line(asbSystem, 'Bus Selector1/1', 'FSEC_Sensor_Monitor/7', ...
    'autorouting', 'on');
add_line(asbSystem, 'ebs_drivercheck/1', 'FSEC_Sensor_Monitor/8', ...
    'autorouting', 'on');

brakeGate = [asbSystem '/Brake_On_Valid_Gate'];
if getSimulinkBlockHandle(brakeGate) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        brakeGate, 'Operator', 'AND', 'Inputs', '2', ...
        'Position', [835 275 885 320]);
end
clear_all_input_lines(brakeGate);
delete_input_line([asbSystem '/brake_on'], 1);
add_line(asbSystem, 'Brake_Sensor_Check/2', 'Brake_On_Valid_Gate/1', ...
    'autorouting', 'on');
add_line(asbSystem, 'FSEC_Sensor_Monitor/1', 'Brake_On_Valid_Gate/2', ...
    'autorouting', 'on');
add_line(asbSystem, 'Brake_On_Valid_Gate/1', 'brake_on/1', ...
    'autorouting', 'on');

safetyNot = [asbSystem '/No_FSEC_Safety_Fault'];
if getSimulinkBlockHandle(safetyNot) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        safetyNot, 'Operator', 'NOT', 'Inputs', '1', ...
        'Position', [795 430 840 460]);
end
delete_input_line(safetyNot, 1);
set_param([asbSystem '/Logical Operator'], 'Inputs', '5');
delete_input_line([asbSystem '/Logical Operator'], 5);
add_line(asbSystem, 'FSEC_Sensor_Monitor/2', ...
    'No_FSEC_Safety_Fault/1', 'autorouting', 'on');
add_line(asbSystem, 'No_FSEC_Safety_Fault/1', ...
    'Logical Operator/5', 'autorouting', 'on');

safetyOut = [asbSystem '/safety_fault'];
if getSimulinkBlockHandle(safetyOut) == -1
    add_block('simulink/Sinks/Out1', safetyOut, 'Port', '3', ...
        'Position', [915 440 945 460]);
end
delete_input_line(safetyOut, 1);
add_line(asbSystem, 'FSEC_Sensor_Monitor/2', 'safety_fault/1', ...
    'autorouting', 'on');

brakeFaultTerminator = [asbSystem '/Brake_Fault_Class_Terminator'];
airFaultTerminator = [asbSystem '/Air_Fault_Class_Terminator'];
if getSimulinkBlockHandle(brakeFaultTerminator) == -1
    add_block('simulink/Sinks/Terminator', brakeFaultTerminator, ...
        'Position', [805 500 825 520]);
end
if getSimulinkBlockHandle(airFaultTerminator) == -1
    add_block('simulink/Sinks/Terminator', airFaultTerminator, ...
        'Position', [805 535 825 555]);
end
delete_input_line(brakeFaultTerminator, 1);
delete_input_line(airFaultTerminator, 1);
add_line(asbSystem, 'FSEC_Sensor_Monitor/3', ...
    'Brake_Fault_Class_Terminator/1', 'autorouting', 'on');
add_line(asbSystem, 'FSEC_Sensor_Monitor/4', ...
    'Air_Fault_Class_Terminator/1', 'autorouting', 'on');

ensure_annotation(asbSystem, ...
    ['Brake sensor open/short confirmation = 100 ms; recovery = 500 ms. ' ...
     'ESP/RES/EBS_Driver fault confirmation = 300 ms. Hydraulic brake ' ...
     'pressure still comes from ESP_T_03.'], ...
    [460 15 1050 65]);

%% Correct the EBS working-side sensor and add pneumatic response checking.
ebsSystem = [model '/EBS'];
workingCompare = [ebsSystem '/Compare To Constant'];
delete_input_line(workingCompare, 1);
add_line(ebsSystem, 'Bus Selector1/2', 'Compare To Constant/1', ...
    'autorouting', 'on');

ebsMonitor = [ebsSystem '/EBS_Response_Monitor'];
if getSimulinkBlockHandle(ebsMonitor) == -1
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        ebsMonitor, 'Position', [555 325 745 445]);
end
ebsMonitorChart = find_em_chart(root, ebsMonitor);
ebsMonitorChart.Script = ebs_monitor_script();
set_param(model, 'SimulationCommand', 'update');
clear_all_input_lines(ebsMonitor);
add_line(ebsSystem, 'Logical Operator/1', 'EBS_Response_Monitor/1', ...
    'autorouting', 'on');
add_line(ebsSystem, 'Bus Selector/1', 'EBS_Response_Monitor/2', ...
    'autorouting', 'on');
add_line(ebsSystem, 'Bus Selector/2', 'EBS_Response_Monitor/3', ...
    'autorouting', 'on');
add_line(ebsSystem, 'Bus Selector1/1', 'EBS_Response_Monitor/4', ...
    'autorouting', 'on');
add_line(ebsSystem, 'Bus Selector1/2', 'EBS_Response_Monitor/5', ...
    'autorouting', 'on');

faultDelay = [ebsSystem '/EBS_Sensor_Fault_Delay'];
if getSimulinkBlockHandle(faultDelay) == -1
    add_block('simulink/Discrete/Unit Delay', faultDelay, ...
        'InitialCondition', 'false', 'SampleTime', '-1', ...
        'Position', [785 360 835 395]);
end
delete_input_line(faultDelay, 1);
add_line(ebsSystem, 'EBS_Response_Monitor/1', ...
    'EBS_Sensor_Fault_Delay/1', 'autorouting', 'on');

ebsFaultOut = [ebsSystem '/ebs_sensor_fault'];
if getSimulinkBlockHandle(ebsFaultOut) == -1
    add_block('simulink/Sinks/Out1', ebsFaultOut, 'Port', '5', ...
        'Position', [885 365 915 385]);
end
delete_input_line(ebsFaultOut, 1);
add_line(ebsSystem, 'EBS_Sensor_Fault_Delay/1', ...
    'ebs_sensor_fault/1', 'autorouting', 'on');

ensure_annotation(ebsSystem, ...
    ['EBS response check: after a trigger with available reservoir pressure, ' ...
     'the cylinder-side pressure must exceed 1.0 bar within 500 ms. ' ...
     'EBS_Driver retains its independent hardware diagnostics.'], ...
    [360 15 1040 65]);

%% Feed the combined fault into the AS state machine without changing root I/O.
faultOr = [model '/FSEC_Safety_Fault_OR'];
if getSimulinkBlockHandle(faultOr) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        faultOr, 'Operator', 'OR', 'Inputs', '2', ...
        'Position', [915 965 970 1010]);
end
clear_all_input_lines(faultOr);
add_line(model, 'ASB_Selfcheck/3', 'FSEC_Safety_Fault_OR/1', ...
    'autorouting', 'on');
add_line(model, 'EBS/5', 'FSEC_Safety_Fault_OR/2', ...
    'autorouting', 'on');

faultDelayRoot = [model '/FSEC_Safety_Fault_Delay'];
if getSimulinkBlockHandle(faultDelayRoot) == -1
    add_block('simulink/Discrete/Unit Delay', faultDelayRoot, ...
        'InitialCondition', 'false', 'SampleTime', '0.01', ...
        'Position', [995 970 1045 1005]);
end
delete_input_line(faultDelayRoot, 1);
add_line(model, 'FSEC_Safety_Fault_OR/1', ...
    'FSEC_Safety_Fault_Delay/1', 'autorouting', 'on');

asSystem = [model '/AS_Stateflow'];
safetyIn = [asSystem '/safety_fault'];
if getSimulinkBlockHandle(safetyIn) == -1
    add_block('simulink/Sources/In1', safetyIn, 'Port', '14', ...
        'OutDataTypeStr', 'boolean', 'Position', [30 690 60 710]);
end

asChart = root.find('-isa', 'Stateflow.Chart', ...
    'Path', [asSystem '/Chart']);
safetyData = find_chart_data(asChart, 'safety_fault');
if isempty(safetyData)
    safetyData = Stateflow.Data(asChart);
    safetyData.Name = 'safety_fault';
    safetyData.Scope = 'Input';
    safetyData.Port = 14;
    set_boolean_type(safetyData);
end

lockData = find_chart_data(asChart, 'safety_lock');
if isempty(lockData)
    lockData = Stateflow.Data(asChart);
    lockData.Name = 'safety_lock';
    lockData.Scope = 'Output';
    lockData.Port = 7;
    lockData.Props.InitialValue = '0';
    lockData.Props.Type.Method = 'Built-in';
    lockData.Props.Type.Primitive = 'double';
end

% Rebuild chart ports after adding Stateflow data.
set_param(model, 'SimulationCommand', 'update');
delete_input_line([asSystem '/Chart'], 14);
add_line(asSystem, 'safety_fault/1', 'Chart/14', 'autorouting', 'on');

lockOut = [asSystem '/safety_lock'];
if getSimulinkBlockHandle(lockOut) == -1
    add_block('simulink/Sinks/Out1', lockOut, 'Port', '7', ...
        'OutDataTypeStr', 'double', 'Position', [985 575 1015 595]);
end
delete_input_line(lockOut, 1);
add_line(asSystem, 'Chart/7', 'safety_lock/1', 'autorouting', 'on');

emergencyState = asChart.find('-isa', 'Stateflow.State', ...
    'Name', 'AS_Emergency');
if ~contains(emergencyState.LabelString, 'safety_lock=1')
    emergencyState.LabelString = sprintf('%s\nsafety_lock=1;', ...
        emergencyState.LabelString);
end

update_as_transitions(asChart);

delete_input_line([model '/AS_Stateflow'], 14);
add_line(model, 'FSEC_Safety_Fault_Delay/1', 'AS_Stateflow/14', ...
    'autorouting', 'on');

lockMemory = [model '/FSEC_Safety_Lock_Memory'];
if getSimulinkBlockHandle(lockMemory) == -1
    add_block('simulink/Signal Routing/Data Store Memory', lockMemory, ...
        'DataStoreName', 'safety_lock', 'InitialValue', '0', ...
        'OutDataTypeStr', 'double', 'Position', [1025 960 1155 995]);
end
lockWrite = [model '/FSEC_Safety_Lock_Write'];
if getSimulinkBlockHandle(lockWrite) == -1
    add_block('simulink/Signal Routing/Data Store Write', lockWrite, ...
        'DataStoreName', 'safety_lock', 'Position', [1185 960 1285 990]);
end
delete_input_line(lockWrite, 1);
add_line(model, 'AS_Stateflow/7', 'FSEC_Safety_Lock_Write/1', ...
    'autorouting', 'on');

%% A software emergency lock forces TS off in the same model step.
tsSystem = [model '/TS_Activation'];
lockReadTs = [tsSystem '/FSEC_Safety_Lock_Read'];
if getSimulinkBlockHandle(lockReadTs) == -1
    add_block('simulink/Signal Routing/Data Store Read', lockReadTs, ...
        'DataStoreName', 'safety_lock', 'Position', [690 455 805 480]);
end
lockNotTs = [tsSystem '/No_FSEC_Safety_Lock'];
if getSimulinkBlockHandle(lockNotTs) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        lockNotTs, 'Operator', 'NOT', 'Inputs', '1', ...
        'Position', [835 450 880 485]);
end
emergencyReadTs = [tsSystem '/AS_Emergency_Read'];
if getSimulinkBlockHandle(emergencyReadTs) == -1
    add_block('simulink/Signal Routing/Data Store Read', emergencyReadTs, ...
        'DataStoreName', 'as_emergency_flag', ...
        'Position', [690 500 805 525]);
end
emergencyNotTs = [tsSystem '/No_AS_Emergency'];
if getSimulinkBlockHandle(emergencyNotTs) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        emergencyNotTs, 'Operator', 'NOT', 'Inputs', '1', ...
        'Position', [835 495 880 530]);
end
tsGate = [tsSystem '/TS_Safety_Gate'];
if getSimulinkBlockHandle(tsGate) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        tsGate, 'Operator', 'AND', 'Inputs', '3', ...
        'Position', [910 385 960 430]);
end
set_param(tsGate, 'Inputs', '3');
delete_input_line(lockNotTs, 1);
delete_input_line(emergencyNotTs, 1);
clear_all_input_lines(tsGate);
delete_input_line([tsSystem '/ts'], 1);
add_line(tsSystem, 'FSEC_Safety_Lock_Read/1', ...
    'No_FSEC_Safety_Lock/1', 'autorouting', 'on');
add_line(tsSystem, 'Chart2/1', 'TS_Safety_Gate/1', 'autorouting', 'on');
add_line(tsSystem, 'No_FSEC_Safety_Lock/1', ...
    'TS_Safety_Gate/2', 'autorouting', 'on');
add_line(tsSystem, 'AS_Emergency_Read/1', ...
    'No_AS_Emergency/1', 'autorouting', 'on');
add_line(tsSystem, 'No_AS_Emergency/1', ...
    'TS_Safety_Gate/3', 'autorouting', 'on');
add_line(tsSystem, 'TS_Safety_Gate/1', 'ts/1', 'autorouting', 'on');
ensure_annotation(tsSystem, ...
    ['AS Emergency forces TS=0 in the same model step; the software lock ' ...
     'keeps TS off until VCU low-voltage power cycle.'], ...
    [610 520 1030 555]);

%% Autonomous torque is permitted only after R2D has completed.
motorSystem = [model '/Motor_Control'];
drivingRead = [motorSystem '/AS_Driving_Read'];
r2dRead = [motorSystem '/R2D_Read'];
lockReadMotor = [motorSystem '/FSEC_Safety_Lock_Read'];
if getSimulinkBlockHandle(drivingRead) == -1
    add_block('simulink/Signal Routing/Data Store Read', drivingRead, ...
        'DataStoreName', 'as_driving_flag', ...
        'Position', [655 580 775 605]);
end
if getSimulinkBlockHandle(r2dRead) == -1
    add_block('simulink/Signal Routing/Data Store Read', r2dRead, ...
        'DataStoreName', 'r2d_flag', 'Position', [655 620 775 645]);
end
if getSimulinkBlockHandle(lockReadMotor) == -1
    add_block('simulink/Signal Routing/Data Store Read', lockReadMotor, ...
        'DataStoreName', 'safety_lock', 'Position', [655 660 775 685]);
end
r2dNot = [motorSystem '/R2D_Complete'];
lockNotMotor = [motorSystem '/No_FSEC_Safety_Lock'];
if getSimulinkBlockHandle(r2dNot) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        r2dNot, 'Operator', 'NOT', 'Inputs', '1', ...
        'Position', [805 615 850 650]);
end
if getSimulinkBlockHandle(lockNotMotor) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        lockNotMotor, 'Operator', 'NOT', 'Inputs', '1', ...
        'Position', [805 655 850 690]);
end
torqueEnable = [motorSystem '/AS_Torque_Enable'];
if getSimulinkBlockHandle(torqueEnable) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        torqueEnable, 'Operator', 'AND', 'Inputs', '4', ...
        'Position', [885 570 940 650]);
end
delete_input_line(r2dNot, 1);
delete_input_line(lockNotMotor, 1);
clear_all_input_lines(torqueEnable);
delete_input_line([motorSystem '/Motor_Torque_Stateflow'], 2);
add_line(motorSystem, 'R2D_Read/1', 'R2D_Complete/1', 'autorouting', 'on');
add_line(motorSystem, 'FSEC_Safety_Lock_Read/1', ...
    'No_FSEC_Safety_Lock/1', 'autorouting', 'on');
add_line(motorSystem, 'as_flag/1', 'AS_Torque_Enable/1', 'autorouting', 'on');
add_line(motorSystem, 'AS_Driving_Read/1', ...
    'AS_Torque_Enable/2', 'autorouting', 'on');
add_line(motorSystem, 'R2D_Complete/1', ...
    'AS_Torque_Enable/3', 'autorouting', 'on');
add_line(motorSystem, 'No_FSEC_Safety_Lock/1', ...
    'AS_Torque_Enable/4', 'autorouting', 'on');
add_line(motorSystem, 'AS_Torque_Enable/1', ...
    'Motor_Torque_Stateflow/2', 'autorouting', 'on');
ensure_annotation(motorSystem, ...
    ['AS torque enable = ASMS AND AS_Driving AND R2D complete AND ' ...
     'no Emergency lock.'], [620 710 1030 745]);

%% Make every combined safety fault visible on the existing EBS error lamp.
ledFaultOr = [model '/FSEC_EBS_Error_OR'];
if getSimulinkBlockHandle(ledFaultOr) == -1
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        ledFaultOr, 'Operator', 'OR', 'Inputs', '2', ...
        'Position', [1755 795 1810 840]);
end
clear_all_input_lines(ledFaultOr);
delete_input_line([model '/Goto13'], 1);
add_line(model, 'LED_Control/4', 'FSEC_EBS_Error_OR/1', ...
    'autorouting', 'on');
add_line(model, 'FSEC_Safety_Fault_OR/1', 'FSEC_EBS_Error_OR/2', ...
    'autorouting', 'on');
add_line(model, 'FSEC_EBS_Error_OR/1', 'Goto13/1', 'autorouting', 'on');

ensure_annotation(model, ...
    ['FSEC preliminary safety layer (2026-07-29): debounced sensor faults, ' ...
     'EBS response diagnostics, Emergency lock, TS shutdown and post-R2D ' ...
     'torque permission. Root interfaces are unchanged.'], ...
    [760 20 1570 70]);

set_param(model, 'SimulationCommand', 'update');
save_system(model);
fprintf('FSEC_MODEL_OPTIMIZATION=PASS\n');
fprintf('MODEL=%s\n', modelFile);
fprintf('BACKUP=%s\n', backupDir);

clear cleanupModel cleanupDir;
end

function text = sensor_monitor_script()
text = sprintf([ ...
    'function [brake_sensor_valid, safety_fault, brake_sensor_fault, air_sensor_fault] = fsec_sensor_monitor(brake_raw_mv, air_ready_raw_mv, air_work_raw_mv, air_ready_bar, air_work_bar, esp_ok, res_ok, ebs_driver_ok)\n' ...
    '%%#codegen\n' ...
    '%% Wide electrical thresholds avoid nuisance trips before final calibration.\n' ...
    'persistent brake_bad brake_good air_bad air_good comm_bad comm_good brake_fault air_fault comm_fault\n' ...
    'if isempty(brake_bad)\n' ...
    '    brake_bad=uint16(0); brake_good=uint16(0); air_bad=uint16(0); air_good=uint16(0);\n' ...
    '    comm_bad=uint16(0); comm_good=uint16(0); brake_fault=false; air_fault=false; comm_fault=false;\n' ...
    'end\n' ...
    'brake_now = (brake_raw_mv < 100.0) || (brake_raw_mv > 4900.0);\n' ...
    'if brake_now\n' ...
    '    brake_good=uint16(0); if brake_bad<uint16(1000), brake_bad=brake_bad+uint16(1); end\n' ...
    '    if brake_bad>=uint16(10), brake_fault=true; end\n' ...
    'else\n' ...
    '    brake_bad=uint16(0); if brake_good<uint16(1000), brake_good=brake_good+uint16(1); end\n' ...
    '    if brake_good>=uint16(50), brake_fault=false; end\n' ...
    'end\n' ...
    '%% 0 V and 10 V are valid endpoints for the 0-10 V air sensors.\n' ...
    '%% Therefore software uses overscale, low reservoir and pair plausibility.\n' ...
    'air_now = (air_ready_raw_mv > 10050.0) || (air_work_raw_mv > 10050.0) || ...\n' ...
    '          (air_ready_bar < 2.5) || (air_work_bar > air_ready_bar + 1.5);\n' ...
    'if air_now\n' ...
    '    air_good=uint16(0); if air_bad<uint16(1000), air_bad=air_bad+uint16(1); end\n' ...
    '    if air_bad>=uint16(50), air_fault=true; end\n' ...
    'else\n' ...
    '    air_bad=uint16(0); if air_good<uint16(1000), air_good=air_good+uint16(1); end\n' ...
    '    if air_good>=uint16(50), air_fault=false; end\n' ...
    'end\n' ...
    'comm_now = (~logical(esp_ok)) || (~logical(res_ok)) || (~logical(ebs_driver_ok));\n' ...
    'if comm_now\n' ...
    '    comm_good=uint16(0); if comm_bad<uint16(1000), comm_bad=comm_bad+uint16(1); end\n' ...
    '    if comm_bad>=uint16(30), comm_fault=true; end\n' ...
    'else\n' ...
    '    comm_bad=uint16(0); if comm_good<uint16(1000), comm_good=comm_good+uint16(1); end\n' ...
    '    if comm_good>=uint16(50), comm_fault=false; end\n' ...
    'end\n' ...
    '%% R2D permission is removed immediately; fault indication remains debounced.\n' ...
    'brake_sensor_valid = (~brake_fault) && (~brake_now);\n' ...
    'brake_sensor_fault = brake_fault;\n' ...
    'air_sensor_fault = air_fault;\n' ...
    'safety_fault = brake_fault || air_fault || comm_fault;\n' ...
    'end\n']);
end

function text = ebs_monitor_script()
text = sprintf([ ...
    'function ebs_sensor_fault = ebs_response_monitor(trigger, asms, driver_ok, air_ready_bar, air_work_bar)\n' ...
    '%%#codegen\n' ...
    '%% EBS_Driver handles electrical faults; VCU verifies pneumatic response.\n' ...
    'persistent last_trigger waiting wait_count relation_count clear_count fault_latched\n' ...
    'if isempty(last_trigger)\n' ...
    '    last_trigger=false; waiting=false; wait_count=uint16(0); relation_count=uint16(0);\n' ...
    '    clear_count=uint16(0); fault_latched=false;\n' ...
    'end\n' ...
    'rising = logical(trigger) && ~last_trigger; last_trigger=logical(trigger);\n' ...
    'if rising && logical(driver_ok) && (air_ready_bar >= 2.5) && (air_work_bar < 1.0)\n' ...
    '    waiting=true; wait_count=uint16(0);\n' ...
    'end\n' ...
    'if waiting\n' ...
    '    if air_work_bar >= 1.0\n' ...
    '        waiting=false; wait_count=uint16(0);\n' ...
    '    else\n' ...
    '        if wait_count<uint16(1000), wait_count=wait_count+uint16(1); end\n' ...
    '        if wait_count>=uint16(50), fault_latched=true; waiting=false; end\n' ...
    '    end\n' ...
    'end\n' ...
    'if air_work_bar > air_ready_bar + 1.5\n' ...
    '    if relation_count<uint16(1000), relation_count=relation_count+uint16(1); end\n' ...
    '    if relation_count>=uint16(20), fault_latched=true; end\n' ...
    'else\n' ...
    '    relation_count=uint16(0);\n' ...
    'end\n' ...
    '%% Recovery is deliberately slow and only allowed outside autonomous mode.\n' ...
    'if (~logical(asms)) && logical(driver_ok) && (air_work_bar < 1.0) && (air_ready_bar >= 2.5)\n' ...
    '    if clear_count<uint16(1000), clear_count=clear_count+uint16(1); end\n' ...
    '    if clear_count>=uint16(100), fault_latched=false; end\n' ...
    'else\n' ...
    '    clear_count=uint16(0);\n' ...
    'end\n' ...
    'ebs_sensor_fault = fault_latched;\n' ...
    'end\n']);
end

function update_as_transitions(chart)
transitions = chart.find('-isa', 'Stateflow.Transition');
for index = 1:numel(transitions)
    transition = transitions(index);
    label = strtrim(transition.LabelString);
    sourceName = object_name(transition.Source);
    destinationName = object_name(transition.Destination);

    if strcmp(destinationName, 'AS_Emergency') && ...
            strcmp(label, '[ebs_working==1]')
        transition.LabelString = ...
            '[ebs_working==1||safety_fault==1||asms_button==0||res_stop==1]';
    elseif strcmp(sourceName, 'AS_Driving') && ...
            strcmp(destinationName, 'AS_Finished') && ...
            contains(label, 'car_spdzero')
        transition.LabelString = ...
            ['[car_spdzero==1&&task_finish==1&&safety_fault==0&&' ...
             'asms_button==1&&res_stop==0]{as_ebs_trig=1}'];
    elseif contains(label, 'after(27,sec)')
        transition.LabelString = ...
            ['after(27,sec)[safety_fault==0&&asms_button==1&&' ...
             'res_stop==0]{as_ebs_trig=1}'];
    elseif strcmp(destinationName, 'AS_Driving') && contains(label, 'res_go')
        transition.LabelString = ...
            ['[res_go==1&&safety_fault==0&&asms_button==1&&' ...
             'res_stop==0]{r2d_warning=T;steer_return=T}'];
    elseif strcmp(destinationName, 'AS_Ready') && contains(label, 'asb_check')
        transition.LabelString = ...
            '[asb_check==1&&safety_fault==0&&safety_lock==0]';
    elseif strcmp(sourceName, 'AS_Off') && ...
            strcmp(destinationName, 'transition')
        transition.LabelString = ...
            ['[as_task==1&&asms_button==1&&safety_fault==0&&' ...
             'safety_lock==0]{brake_flag=2}'];
    elseif strcmp(sourceName, 'AS_Off') && contains(label, 'ami_manualdriving')
        transition.LabelString = ...
            '[ami_manualdriving==1&&safety_fault==0&&safety_lock==0]';
    end
end
end

function name = object_name(object)
if isempty(object)
    name = '';
elseif isa(object, 'Stateflow.State')
    name = object.Name;
else
    name = '';
end
end

function data = find_chart_data(chart, name)
data = chart.find('-isa', 'Stateflow.Data', 'Name', name);
if numel(data) > 1
    data = data(1);
end
end

function set_boolean_type(data)
data.Props.Type.Method = 'Built-in';
data.Props.Type.Primitive = 'boolean';
end

function chart = find_em_chart(root, blockPath)
charts = root.find('-isa', 'Stateflow.EMChart');
chart = [];
for index = 1:numel(charts)
    fullPath = [charts(index).Path '/' charts(index).Name];
    if strcmp(charts(index).Path, blockPath) || strcmp(fullPath, blockPath)
        chart = charts(index);
        break;
    end
end
if isempty(chart)
    error('MATLAB Function chart not found for %s.', blockPath);
end
end

function replace_input_line(block, portNumber, system, source, destination, name)
delete_input_line(block, portNumber);
line = add_line(system, source, destination, 'autorouting', 'on');
set_param(line, 'Name', name);
end

function delete_input_line(block, portNumber)
handles = get_param(block, 'LineHandles');
if portNumber <= numel(handles.Inport) && handles.Inport(portNumber) ~= -1
    delete_line(handles.Inport(portNumber));
end
end

function clear_all_input_lines(block)
handles = get_param(block, 'LineHandles');
for index = 1:numel(handles.Inport)
    if handles.Inport(index) ~= -1
        delete_line(handles.Inport(index));
    end
end
end

function ensure_annotation(system, text, position)
annotations = find_system(system, 'FindAll', 'on', 'SearchDepth', 1, ...
    'Type', 'annotation');
for index = 1:numel(annotations)
    if strcmp(get_param(annotations(index), 'PlainText'), text)
        return;
    end
end
annotation = Simulink.Annotation(system, text);
annotation.Position = position;
end
